### ISSUE TITLE
request: mengisi nilai outlier dengan median

### ISSUE THREAD

**Issue by taruma** [taruma/hidrokit#13]
Outlier dataset akan diisi dengan nilai median (atau dapat ditambahkan dengan metode lainnya).

# To-do
- [ ] Buat cabang baru khusus fitur ini.
- [ ] Buat fungsi di `datakit`
- [ ] Tambah informasi di contoh penggunaan (_notebook_).
- [ ] Pastikan semuanya sudah oke
- [ ] Merge

# Referensi
- https://stackoverflow.com/questions/45386955/python-replacing-outliers-values-with-median-values

**Comment by taruma** [comment]
pindahin ke 0.2.x
