### ISSUE TITLE
ask: daftar berbagai metode praktis

### ISSUE THREAD

**Issue by taruma** [taruma/hidrokit#14]
Daftar metode yang digunakan dalam bidang hidrologi:
- ...
- ...

# To-do
- [ ] Buat daftar berbagai metode yang digunakan dalam bidang hidrologi/sumber daya air.
- [ ] Memiliki referensi yang jelas.
- [ ] Menambahkan dalam agenda pengembangan metode di hidrokit.

**Comment by taruma** [comment]
ditutup karena akhir pengembangan dari saya.
